services:
  book-club:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/book
    environment:
      - DB_NAME=books_db
      - DB_USER=books_user
      - DB_PSWD=3241
      - DB_HOST=db
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: postgres:14.6-alpine3.16
    environment:
      - POSTGRES_DB=books_db
      - POSTGRES_USER=books_user
      - POSTGRES_PASSWORD=3241

