# Generated by Django 4.2 on 2024-01-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_comment_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="book",
            name="pdf",
            field=models.FileField(blank=True, null=True, upload_to="books/"),
        ),
    ]
