# Generated by Django 4.2 on 2024-01-06 23:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0003_alter_book_image_alter_book_pdf"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="image",
            new_name="image_card",
        ),
        migrations.AddField(
            model_name="book",
            name="image_detail",
            field=models.ImageField(blank=True, null=True, upload_to="images_detail/"),
        ),
    ]
