# Generated by Django 4.2 on 2024-01-07 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0004_rename_image_book_image_card_book_image_detail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
